/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.student.project;

import com.google.common.base.Strings;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {

        TextField courseField = new TextField();


        ObservableList<String> gradeList = FXCollections.observableArrayList("A","A-","B+","B","C+","C","C-","D+","D","D","D-","F");
        Button calculate = new Button();
        calculate.setOnAction(event -> {

        });





        Label courseLabel = new Label("Courses");
        Label gradeLabel = new Label("Grades");
        Label creditLabel = new Label("Credits");



        ComboBox<String> grades = new ComboBox<>();
        grades.getItems().addAll(gradeList);





        BorderPane pane = new BorderPane(grades);

        Scene scene = new Scene(pane, 600,400);
        primaryStage.setTitle("GPA-CALCULATOR");
        primaryStage.setScene(scene);
        primaryStage.show();

    }
}
